name: Create Release PR

on:
  workflow_dispatch:

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update Draft
        uses: release-drafter/release-drafter@v5.15.0
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.7.0

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Prep Release
        run: |
          TAG="${{ steps.draft.outputs.tag_name }}"
          CHANGELOG_FULL=&(cat << EOS
          ${{ steps.draft.outputs.body }}
          EOS)
          export VERSION="${TAG#v}.0.0.0"
          export CHANGELOG="$(echo ${CHANGELOG_FULL} | grep '*')"

          yq eval ".version = env(VERSION) | .changelog = env(CHANGELOG)" build.yaml
          sed -i **/*.csproj \
            -e "s;<AssemblyVersion>.*;<AssemblyVersion>${VERSION}</AssemblyVersion>;" \
            -e "s;<FileVersion>.*;<FileVersion>${VERSION}</FileVersion>;"
          
      - name: create or update PR
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          title: 'Prepare for release ${{ steps.draft.outputs.tag_name }}'
          body: |
            :robot: This PR was automatically created as a preration for the next plugin release.

            ---

            ${{ steps.draft.outputs.body }}
          branch: "release-prep-${{ steps.draft.outputs.tag_name }}"
          commit-message: 'bump version for ${{ steps.draft.outputs.tag_name }}'
          author: "jellyfin-bot <team@jellyfin.org>"
          labels:  'release-prep, skip-changelog'
