name: Create Release PR

on:
  workflow_dispatch:

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update Draft
        uses: release-drafter/release-drafter@v5.15.0
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.7.0

      - name: Export draft output as EnvVars
        run: |
          TAG="${{ steps.draft.outputs.tag_name }}"
          cat << EOS >> cl.txt
          ${{ steps.draft.outputs.body }}
          EOS;
          echo "VERSION=${TAG#v}.0.0.0" >> $GITHUB_ENV
          echo "CHANGELOG='$(cat cl.txt | grep '*')'" >> $GITHUB_ENV
          rm cl.txt

      - name: Create or Update release PR
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            yq eval '.version = "${{ env.VERSION }}" | .changelog = "${{ env.CHANGELOG }}"' build.yaml
            sed -i **/*.csproj \
              -e "s;<AssemblyVersion>.*;<AssemblyVersion>${{ env.VERSION }}</AssemblyVersion>;" \
              -e "s;<FileVersion>.*;<FileVersion>${{ env.VERSION }}</FileVersion>;"
          COMMIT_MESSAGE: 'bump version for ${{ steps.draft.outputs.tag_name }}'
          COMMIT_NAME: 'jellyfin-bot'
          COMMIT_EMAIL: 'team@jellyfin.org'
          PR_BRANCH_PREFIX: 'release-prep-'
          PR_BRANCH_NAME: '${{ steps.draft.outputs.tag_name }}'
          PR_TITLE: 'Prepare for release ${{ steps.draft.outputs.tag_name }}'
          PR_BODY: '${{ steps.draft.outputs.body }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
