name: Release Automation

on:
  issue_comment:

jobs:
  merge_release_prepr_pr:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@h1dden-bot release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify as seen
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          edit-mode: replace
          reactions: '+1'

      - name: Try Merge PR
        uses: reitermarkus/automerge@v1.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          pull-request: ${{ github.event.issue.number }}
          dry-run: true

  release_new_version:
    needs: merge_release_prepr_pr
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    environment: release
    steps:
      - run: echo "wip"
